//! The message model `harness`'s loop and clients operate on — modeled on
//! `earendil-works/pi`'s `packages/ai/src/types.ts`, per issue #93.
//!
//! `Message` here is a different concept from the one CONTEXT.md's "Terms
//! we avoid" section rules out. That entry is about Reflection's
//! user-facing Conversation, which stays Questions and Answers, never
//! "messages" — a Question has no addressee, so calling it a message
//! smuggles in a property it doesn't have. `Message` in this module is the
//! wire-protocol level underneath that: what is actually sent to and read
//! back from a chat endpoint. `llm::ChatMessage` already names a plainer
//! version of the same idea (a bare `role`/`content` pair) for exactly the
//! same reason — this module's `Message` is a richer version of that same
//! non-domain concept, not a second name for a Question or an Answer.

use serde_json::Value;

/// One tool the model may ask to run, described by a JSON Schema for its
/// arguments. `harness` never constructs one of these itself — pass 2 (or
/// a later ticket) defines the actual tools, `entries_in_range` first —
/// this type only fixes the shape a `Tool` must have to be rendered into a
/// prompt (`prompted::PromptedToolClient`), or, if the configured endpoint
/// ever grows genuine tool-calling, into a real tool-call request.
#[derive(Debug, Clone, PartialEq)]
pub struct Tool {
    pub name: String,
    pub description: String,
    /// A JSON Schema object describing the shape `arguments` must have.
    pub parameters: Value,
}

/// One piece of an `AssistantMessage`'s reply, in the order the model
/// produced it. A reply is a `Vec` of these rather than a single value
/// because — per the wire format `prompted::PromptedToolClient` parses —
/// one reply can freely mix prose and one or more tool calls: narrating a
/// little, calling a tool, narrating a little more, is something the
/// configured model actually does unprompted (issue #93's prototype).
#[derive(Debug, Clone, PartialEq)]
pub enum ContentBlock {
    /// Prose. Everything outside a `<tool_call>` tag becomes one of these
    /// — see `prompted`'s scanner.
    Text(String),
    /// A request to run one tool. `id` is generated by the parser, not the
    /// model — the wire format carries no id of its own (see
    /// `prompted`'s doc comment) — and exists purely so a later
    /// `Message::ToolResult` can name which call it answers.
    ///
    /// An empty `name` is a reserved sentinel meaning "this was clearly an
    /// attempted tool call — the reply did contain a `<tool_call>` tag —
    /// but the parser could not make out which tool was being asked for at
    /// all" (an unterminated tag at end of stream, interior text that
    /// isn't a JSON object, or a missing/non-string `name` field inside
    /// it). This is deliberately distinct from a non-empty but
    /// unrecognised name: this type only ever describes what the reply
    /// *looked like*, never whether the named tool actually exists — that
    /// judgment belongs to pass 2's loop, which is expected to turn both
    /// cases into an ordinary, recoverable `Message::ToolResult { is_error:
    /// true, .. }` rather than treat either as a failure.
    ToolCall {
        id: String,
        name: String,
        arguments: Value,
    },
}

/// Why an `AssistantMessage`'s stream ended. Grouped the way `pi`'s is,
/// because pass 2's loop is written against exactly this set: "keep
/// looping while `ToolUse`, stop and hand back the reply on anything else"
/// is the entire stopping rule, and it only holds if this enum is the one
/// place that decision gets encoded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StopReason {
    /// A complete reply, with no tool call in it — pass 2's loop reads
    /// this as the Answer and stops. Also covers a reply whose *content*
    /// is malformed (bad tool-call JSON, an unrecognised tool name): those
    /// are recoverable inside pass 2's loop by construction, never a
    /// stream failure — see `ContentBlock::ToolCall`'s doc comment.
    Stop,
    /// The model hit a length/token limit mid-reply.
    Length,
    /// `content` contains at least one `ContentBlock::ToolCall`. Computed
    /// once by whatever produced the `AssistantMessage`, so pass 2 never
    /// has to re-derive it by scanning `content` itself.
    ToolUse,
    /// The request or the model itself failed outright — a non-2xx, a
    /// connection error, a timeout. This is the one contract every
    /// `chat::ChatClient` must honour (see that module's doc comment): a
    /// failure like this is *always* delivered as a terminal
    /// `AssistantMessage` carrying this variant and `error_message`, never
    /// as an `Err` out of the stream — so pass 2's loop has exactly one
    /// shape to handle for "something went wrong," not two.
    Error,
    /// The caller cancelled the request before the model finished.
    Aborted,
}

/// Coarse token accounting, when the underlying endpoint reports it. Kept
/// as a real field from the start (matching `pi`), for exactly the reason
/// this comment used to point at: issue #97 is the "later ticket" that
/// wires it up, and it changed a value, not this type's shape.
///
/// Populated for real as of issue #97:
/// `harness::prompted::PromptedToolClient::stream` builds this from
/// `llm::ChatReply::usage`, which `llm::OpenAiCompatibleClient::chat`
/// itself reads off the configured endpoint's own response (`llm::parse_usage`).
/// `input_tokens`/`output_tokens` here are that same call's
/// `prompt_tokens`/`completion_tokens` under `harness`'s own naming — see
/// `PromptedToolClient::stream`'s doc comment for why the rename happens at
/// that one seam rather than either module adopting the other's vocabulary.
///
/// **`Some(Usage)` is only ever a real measurement.** `llm::parse_usage`
/// already treats an endpoint's `usage` field being absent, all-zero, or
/// malformed as "unknown" and returns `None` for all three — never
/// `Some(Usage { 0, 0 })` — so `compaction::estimate_tokens`'s anchor search
/// (`Message::Assistant` usage) can trust any `Some` it finds at face
/// value without re-checking it for zero itself. A test double is still
/// free to construct `Usage::default()` directly (nothing prevents it, and
/// existing tests unrelated to token accounting do) — that's a fixture
/// choice, not something this type or `parse_usage` can see or guard
/// against; it just isn't how a real `Some(Usage)` ever reaches here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Usage {
    pub input_tokens: u32,
    pub output_tokens: u32,
}

/// A completed — or terminally failed — reply from the model. Always the
/// payload of the last event a `chat::AssistantMessageStream` yields.
#[derive(Debug, Clone, PartialEq)]
pub struct AssistantMessage {
    pub content: Vec<ContentBlock>,
    pub stop_reason: StopReason,
    /// Set when `stop_reason` is `Error`; `None` otherwise, including on
    /// `Length` — a truncation is not a failure this field explains, it's
    /// visible directly from `stop_reason` itself.
    pub error_message: Option<String>,
    pub usage: Option<Usage>,
}

/// One turn in `Context::messages`, at the wire-protocol level this
/// module's doc comment describes.
#[derive(Debug, Clone, PartialEq)]
pub enum Message {
    /// A Question, or — via `prompted::PromptedToolClient` — a
    /// `ToolResult` re-rendered for a wire with no `tool` role of its own.
    /// See that module for how the two are told apart on the wire.
    User(String),
    /// A complete prior reply from the model, replayed verbatim (including
    /// any `ToolCall` blocks it made) so the model sees its own history
    /// exactly as it produced it, rather than a paraphrase of it.
    Assistant(AssistantMessage),
    /// What running one tool call produced, addressed back to the specific
    /// call that asked for it. There is no `tool` role in this protocol —
    /// see `prompted::PromptedToolClient` for how this becomes a `user`
    /// message on the wire without losing which call it answers.
    ToolResult {
        tool_call_id: String,
        tool_name: String,
        /// The compact, model-facing rendering of what the tool found —
        /// never the richer structured detail a later ticket's interface
        /// renders from the same call (issue #93's "two payloads"
        /// requirement: a compact rendering the model reads, and
        /// structured detail the interface renders, which the model never
        /// sees). `harness` carries only this half; the structured half
        /// belongs to whatever a tool call returns, not to the message
        /// model itself.
        content: String,
        is_error: bool,
    },
}

/// Everything one call to a `chat::ChatClient` needs: the system prompt,
/// the Conversation so far in wire-protocol `Message`s (not Reflection's
/// `SessionTurnRow`s — pass 2's loop is what translates between the two),
/// and the tools available this turn.
#[derive(Debug, Clone, PartialEq)]
pub struct Context {
    pub system_prompt: String,
    pub messages: Vec<Message>,
    pub tools: Vec<Tool>,
}
