#!/usr/bin/env bash
# Run once per machine. Creates the two locally-generated signing identities
# this project uses in place of an Apple Developer or Play Store account —
# neither exists, and neither will (docs/adr/0015-locally-generated-release-signing-identities.md).
#
# macOS half: a dedicated keychain holding a self-signed code-signing
# certificate, imported for codesign and with its key partition list set so
# builds never prompt. Safe to re-run — it deletes and recreates the
# keychain each time, so a fresh cert costs nothing on macOS.
#
# Android half: a release keystore at ~/.meologue/, outside the repo, plus a
# gitignored apps/android/keystore.properties pointing at it. NOT safe to
# blindly re-run: a new key can no longer sign upgrades over whatever this
# key has already installed on a device, and that is unrecoverable. This
# script refuses to touch an existing keystore.
#
# Usage: ./scripts/setup-signing.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ---------------------------------------------------------------------------
# macOS: dedicated keychain + self-signed code-signing certificate
# ---------------------------------------------------------------------------

CERT_NAME="meologue Dev"
KEYCHAIN="$HOME/Library/Keychains/meologue-signing.keychain-db"
KEYCHAIN_PASS="$(openssl rand -base64 24)"

echo "==> macOS: (re)creating signing keychain"

security delete-keychain "$KEYCHAIN" 2>/dev/null || true

security create-keychain -p "$KEYCHAIN_PASS" "$KEYCHAIN"
security unlock-keychain -p "$KEYCHAIN_PASS" "$KEYCHAIN"
security set-keychain-settings -u "$KEYCHAIN" # disable auto-lock

# Add to the user's keychain search list alongside the login keychain, so
# codesign finds this identity without -k.
security list-keychains -d user -s "$HOME/Library/Keychains/login.keychain-db" "$KEYCHAIN"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

openssl req -x509 -newkey rsa:2048 \
  -keyout "$WORK_DIR/key.pem" -out "$WORK_DIR/cert.pem" \
  -days 3650 -nodes -subj "/CN=$CERT_NAME" \
  -addext "keyUsage=critical,digitalSignature" \
  -addext "extendedKeyUsage=codeSigning"

openssl pkcs12 -export -out "$WORK_DIR/cert.p12" \
  -inkey "$WORK_DIR/key.pem" -in "$WORK_DIR/cert.pem" \
  -passout pass:"$KEYCHAIN_PASS"

security import "$WORK_DIR/cert.p12" -P "$KEYCHAIN_PASS" -T /usr/bin/codesign -k "$KEYCHAIN"

# Without this, every codesign invocation (every build) prompts for the
# keychain password interactively.
security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASS" "$KEYCHAIN"

echo "    '$CERT_NAME' installed in $KEYCHAIN"
echo "    (security find-identity -v -p codesigning reports 0 identities for a"
echo "    self-signed cert like this one -- drop -v to actually see it; codesign"
echo "    uses it fine either way.)"

# ---------------------------------------------------------------------------
# Android: release keystore, kept outside the repo
# ---------------------------------------------------------------------------

MEOLOGUE_DIR="$HOME/.meologue"
KEYSTORE_PATH="$MEOLOGUE_DIR/release.keystore"
KEYSTORE_PROPERTIES="$ROOT_DIR/apps/android/keystore.properties"
KEY_ALIAS="meologue"

echo "==> Android: release keystore"

if [ -f "$KEYSTORE_PATH" ]; then
  echo "    $KEYSTORE_PATH already exists -- refusing to touch it."
  echo "    A new key can no longer sign upgrades over what it's already"
  echo "    installed on a device, and there is no way to recover from that."
  echo "    Delete it yourself first if you really mean to start over."
  if [ -f "$KEYSTORE_PROPERTIES" ]; then
    echo "    $KEYSTORE_PROPERTIES already points at it; leaving it alone."
  else
    echo "    WARNING: $KEYSTORE_PROPERTIES is missing even though the"
    echo "    keystore exists. Recreate it by hand -- this script won't"
    echo "    generate one without also generating the keystore it describes."
  fi
else
  mkdir -p "$MEOLOGUE_DIR"
  chmod 700 "$MEOLOGUE_DIR"

  # One password for both store and key: modern `keytool` defaults to a
  # PKCS12 keystore, which doesn't support a key password different from the
  # store password (it silently ignores -keypass if you pass a different
  # one), so keeping them equal here matches what actually gets stored.
  STORE_PASS="$(openssl rand -base64 24)"
  KEY_PASS="$STORE_PASS"

  keytool -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$STORE_PASS" -keypass "$KEY_PASS" \
    -dname "CN=meologue, OU=Dev, O=meologue, L=, ST=, C=US"

  chmod 600 "$KEYSTORE_PATH"

  cat >"$KEYSTORE_PROPERTIES" <<EOF
# Generated by scripts/setup-signing.sh. Gitignored -- never commit this file.
storeFile=$KEYSTORE_PATH
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASS
EOF
  chmod 600 "$KEYSTORE_PROPERTIES"

  echo "    Created $KEYSTORE_PATH"
  echo "    Wrote $KEYSTORE_PROPERTIES"
fi

echo "==> Done."
